### ISSUE TITLE
Multi-column mode

### ISSUE THREAD

**Issue by drfiresign** [ushnisha/tranquility-reader-webextensions#34]
Hi, I was wondering if it was possible to include a multi-column option in your extension. 

This would allow someone with a wider monitor to read several columns of text at once. So instead of having a large amount of space on either side of the text, or having to track very long lines of text across the page, the user could read lines of reasonable text width across multiple columns allowing them to see most of the page at once.

I'm sure there's a better way to do this but I found some CSS that I was able to add to the built-in Reader Mode which added multiple columns and this was the relevant section from it. The rest was all making the color style match the Reader Mode page.

```css
.container {
    margin: 25px 25px 25px 25px !important;
    max-width: 2400px !important;
    column-width: 550px !important;
    column-gap: 20px !important;
    column-count: 4 !important;
}
```

I'm sure this feature would require much more than just adding a couple of rules where appropriate of course. There would likely need to be a way to enable and disable the option for those who don't want it or perhaps it would auto break into columns if the page width hits a certain threshold. I wouldn't presume to know how best to implement it, but maybe you'd find this an interesting addition to your extension?

In any case, thank you for taking the time to read my idea!
